#!/usr/bin/env bun
/**
 * Initialize agent-orchestrator.yaml configuration
 * 
 * Usage:
 *   bun init-config.ts [options]
 * 
 * Options:
 *   --repo <url>        Repository URL (default: auto-detect)
 *   --port <number>     Dashboard port (default: 3000)
 *   --agent <name>      Agent plugin (default: claude-code)
 *   --runtime <name>    Runtime plugin (default: tmux)
 */

import { $ } from "bun";
import { parseArgs } from "util";
import { existsSync, writeFileSync, readFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";

const args = parseArgs({
  options: {
    repo: { type: "string", short: "r" },
    port: { type: "string", short: "p", default: "3000" },
    agent: { type: "string", short: "a", default: "claude-code" },
    runtime: { type: "string", default: "tmux" },
    yes: { type: "boolean", short: "y", default: false },
  },
  strict: false,
});

async function detectGitInfo() {
  try {
    const remote = await $`git remote get-url origin`.quiet();
    const branch = await $`git rev-parse --abbrev-ref HEAD`.quiet();
    const repoPath = await $`pwd`.quiet();
    
    const remoteUrl = remote.stdout.toString().trim();
    const branchName = branch.stdout.toString().trim();
    const currentPath = repoPath.stdout.toString().trim();
    
    // Parse owner/repo from remote URL
    let ownerRepo = "";
    if (remoteUrl.includes("github.com")) {
      const match = remoteUrl.match(/github\.com[\/:]([^\/]+\/[^\/\.]+)/);
      if (match) ownerRepo = match[1].replace(".git", "");
    }
    
    return {
      repo: ownerRepo,
      path: currentPath,
      branch: branchName,
    };
  } catch (e) {
    return null;
  }
}

async function main() {
  console.log("🔧 Agent Orchestrator Config Generator\n");
  
  const gitInfo = await detectGitInfo();
  
  const repo = args.values.repo || gitInfo?.repo || "owner/repo";
  const path = gitInfo?.path || process.cwd();
  const branch = gitInfo?.branch || "main";
  const port = parseInt(args.values.port);
  const agent = args.values.agent;
  const runtime = args.values.runtime;
  
  const config = `# Agent Orchestrator Configuration
# Generated by init-config.ts

port: ${port}
dataDir: ~/.agent-orchestrator
worktreeDir: ~/.worktrees

defaults:
  runtime: ${runtime}
  agent: ${agent}
  workspace: worktree
  notifiers: [desktop]

projects:
  my-app:
    repo: ${repo}
    path: ${path}
    defaultBranch: ${branch}
    sessionPrefix: app

reactions:
  ci-failed:
    auto: true
    action: send-to-agent
    retries: 2
    escalateAfter: 2

  changes-requested:
    auto: true
    action: send-to-agent
    escalateAfter: 30m

  approved-and-green:
    auto: false
    action: notify
`;

  const configPath = join(path, "agent-orchestrator.yaml");
  
  if (existsSync(configPath) && !args.values.yes) {
    console.log(`⚠️  Config file already exists: ${configPath}`);
    console.log("Use --yes to overwrite");
    process.exit(1);
  }
  
  writeFileSync(configPath, config);
  console.log(`✅ Created: ${configPath}`);
  console.log(`\n📊 Dashboard: http://localhost:${port}`);
  console.log(`📁 Repo: ${repo}`);
  console.log(`🌿 Branch: ${branch}`);
  console.log(`\n🚀 Next steps:`);
  console.log(`   ao spawn my-app ISSUE-NUMBER`);
  console.log(`   ao status`);
}

main().catch(console.error);
