import type { Rank, RoutePath } from '../types';

export const BIBLE_VERSES = [
  "For by grace you have been saved through faith. And this is not your own doing; it is the gift of God. - Ephesians 2:8",
  "The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you. - Numbers 6:24-25",
  "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.' - 2 Corinthians 12:9",
  "Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need. - Hebrews 4:16",
  "But grow in the grace and knowledge of our Lord and Savior Jesus Christ. - 2 Peter 3:18",
  "Give, and it will be given to you. A good measure, pressed down, shaken together and running over. - Luke 6:38",
  "Trust in the Lord with all your heart and lean not on your own understanding. - Proverbs 3:5",
  "I can do all things through Christ who strengthens me. - Philippians 4:13",
  "The Lord is my shepherd; I shall not want. - Psalm 23:1",
  "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go. - Joshua 1:9"
];

// South African slang/phrases for authentic feel
export const SA_SLANG = {
  greetings: ["Sho!", "Howzit!", "Sharp sharp!", "Yebo!", "Sawubona!"],
  affirmations: ["Sharp!", "Kiff!", "Lekker!", "Bo!", "Eita!"],
  farewells: ["Hamba kahle", "Sharp!", "Go well", "Cheers!"],
  encouragement: ["Aikona!", "Hou koers!", "Moer!", "Vasbyt!"],
  taxiTerms: ["traansie", "kombi", "quantum", "taxi", "rank"],
  driverTerms: ["Baba", "Malume", "Skhokho", "Boss", "Chief"],
  passengerTerms: ["sisi", "bhuti", "mama", "tata"]
};

// Comprehensive Johannesburg Taxi Ranks - expanded with more locations
export const TAXI_RANKS: Rank[] = [
  // Johannesburg CBD Taxi Ranks
  { id: 'noord', name: 'Noord Street (MTN / Park Central)', location: 'Joburg CBD', category: 'CBD', coords: { x: 52, y: 48 } },
  { id: 'bree', name: 'Bree Street (Metro Mall)', location: 'Joburg CBD', category: 'CBD', coords: { x: 48, y: 52 } },
  { id: 'wanderers', name: 'Wanderers Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 55, y: 45 } },
  { id: 'faraday', name: 'Faraday Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 50, y: 58 } },
  { id: 'sophie', name: 'Sophie de Bruyn Street Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 42, y: 50 } },
  { id: 'gandhi', name: 'Gandhi Square Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 50, y: 53 } },
  { id: 'park-station', name: 'Park Station Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 51, y: 46 } },
  { id: 'ferreirasdorp', name: 'Ferreirasdorp Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 46, y: 55 } },
  { id: 'bosman', name: 'Bosman Station Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 50, y: 15 } },
  { id: 'durban-vb', name: 'Durban Taxi Rank (52 Van Beek St)', location: 'Joburg CBD', category: 'CBD', coords: { x: 56, y: 50 } },
  { id: 'jeppe', name: 'Jeppe Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 60, y: 52 } },
  { id: 'hillbrow-cbd', name: 'Hillbrow Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 53, y: 42 } },
  { id: 'yeoville-market', name: 'Yeoville Market Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 58, y: 38 } },
  { id: 'eloff-street', name: 'Eloff Street Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 49, y: 51 } },
  { id: 'commissioner', name: 'Commissioner Street Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 47, y: 54 } },
  { id: 'marshalltown', name: 'Marshalltown Taxi Rank', location: 'Joburg CBD', category: 'CBD', coords: { x: 50, y: 56 } },
  
  // Soweto Taxi Ranks - expanded
  { id: 'bara', name: 'Bara Taxi Rank (Chris Hani)', location: 'Soweto', category: 'Soweto', coords: { x: 25, y: 75 } },
  { id: 'dube', name: 'Soweto Dube Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 20, y: 70 } },
  { id: 'protea-s', name: 'Protea South Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 15, y: 85 } },
  { id: 'jabulani', name: 'Jabulani Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 18, y: 78 } },
  { id: 'white-city', name: 'White City Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 22, y: 82 } },
  { id: 'dobsonville', name: 'Dobsonville Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 12, y: 65 } },
  { id: 'nancefield', name: 'Nancefield Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 28, y: 88 } },
  { id: 'emdeni', name: 'Emdeni Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 10, y: 72 } },
  { id: 'kliptown', name: 'Kliptown Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 24, y: 86 } },
  { id: 'orlando', name: 'Orlando Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 28, y: 68 } },
  { id: 'pimville', name: 'Pimville Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 32, y: 80 } },
  { id: 'tladi', name: 'Tladi Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 14, y: 76 } },
  { id: 'moletsane', name: 'Moletsane Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 16, y: 74 } },
  { id: 'mapetla', name: 'Mapetla Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 18, y: 84 } },
  { id: 'molapo', name: 'Molapo Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 20, y: 80 } },
  { id: 'senaoane', name: 'Senaoane Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 22, y: 78 } },
  { id: 'zola', name: 'Zola Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 8, y: 70 } },
  { id: 'zondi', name: 'Zondi Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 10, y: 68 } },
  { id: 'protea-n', name: 'Protea North Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 12, y: 82 } },
  { id: 'chris-hani', name: 'Chris Hani Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 26, y: 73 } },
  { id: 'phiri', name: 'Phiri Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 24, y: 72 } },
  { id: 'mofolo-s', name: 'Mofolo South Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 16, y: 68 } },
  { id: 'mofolo-n', name: 'Mofolo North Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 14, y: 66 } },
  { id: 'dhlamini', name: 'Dhlamini Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 20, y: 86 } },
  { id: 'chiawelo', name: 'Chiawelo Taxi Rank', location: 'Soweto', category: 'Soweto', coords: { x: 18, y: 88 } },
  
  // Alexandra Taxi Ranks - expanded
  { id: 'alex-15th', name: '15th Avenue Taxi Rank', location: 'Alexandra', category: 'Alexandra', coords: { x: 75, y: 28 } },
  { id: 'alex-mall', name: 'Alex Mall (Pan Africa)', location: 'Alexandra', category: 'Alexandra', coords: { x: 78, y: 25 } },
  { id: 'alex-john-brandt', name: '15th Ave & John Brandt Corner', location: 'Alexandra', category: 'Alexandra', coords: { x: 74, y: 27 } },
  { id: 'alex-20th', name: '20th Avenue Corner Locations', location: 'Alexandra', category: 'Alexandra', coords: { x: 76, y: 30 } },
  { id: 'alex-selborne', name: 'Selborne Street Locations', location: 'Alexandra', category: 'Alexandra', coords: { x: 75, y: 24 } },
  { id: 'alexandra-g', name: 'Alexandra Taxi Rank', location: 'Alexandra', category: 'Alexandra', coords: { x: 77, y: 28 } },
  { id: 'alex-1st', name: '1st Avenue Taxi Rank', location: 'Alexandra', category: 'Alexandra', coords: { x: 72, y: 26 } },
  { id: 'alex-8th', name: '8th Avenue Taxi Rank', location: 'Alexandra', category: 'Alexandra', coords: { x: 73, y: 29 } },
  { id: 'alex-westbank', name: 'Westbank Taxi Rank', location: 'Alexandra', category: 'Alexandra', coords: { x: 79, y: 22 } },
  { id: 'alex-london', name: 'London Road Taxi Rank', location: 'Alexandra', category: 'Alexandra', coords: { x: 76, y: 32 } },
  
  // Greater Johannesburg Metropolitan Area
  { id: 'krugersdorp', name: 'Krugersdorp Taxi Rank', location: 'West Rand', category: 'Greater Joburg', coords: { x: 5, y: 40 } },
  { id: 'tembisa-plaza', name: 'Tembisa Plaza Taxi Rank', location: 'Ekurhuleni', category: 'Greater Joburg', coords: { x: 85, y: 15 } },
  { id: 'westgate-g', name: 'Westgate Taxi Rank', location: 'Roodepoort', category: 'Greater Joburg', coords: { x: 20, y: 45 } },
  { id: 'midrand-g', name: 'Midrand Taxi Rank', location: 'Midrand', category: 'Greater Joburg', coords: { x: 65, y: 10 } },
  { id: 'fourways-g', name: 'Fourways Taxi Rank', location: 'Fourways', category: 'Greater Joburg', coords: { x: 45, y: 15 } },
  { id: 'randburg-g', name: 'Randburg Taxi Rank', location: 'Randburg', category: 'Greater Joburg', coords: { x: 40, y: 25 } },
  { id: 'roodepoort-g', name: 'Roodepoort Taxi Rank', location: 'Roodepoort', category: 'Greater Joburg', coords: { x: 25, y: 40 } },
  { id: 'sandton-g', name: 'Sandton Taxi Rank', location: 'Sandton', category: 'Greater Joburg', coords: { x: 60, y: 20 } },
  { id: 'diepsloot-g', name: 'Diepsloot Taxi Rank', location: 'North', category: 'Greater Joburg', coords: { x: 48, y: 2 } },
  { id: 'ivory-park', name: 'Ivory Park Taxi Rank', location: 'Ekurhuleni', category: 'Greater Joburg', coords: { x: 88, y: 12 } },
  { id: 'blue-lagoon', name: 'Blue Lagoon Taxi Rank', location: 'Ekurhuleni', category: 'Greater Joburg', coords: { x: 82, y: 18 } },
  { id: 'germiston-g', name: 'Germiston Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 80, y: 60 } },
  { id: 'alberton-g', name: 'Alberton Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 70, y: 75 } },
  { id: 'thokoza-g', name: 'Thokoza Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 75, y: 85 } },
  { id: 'duduza-g', name: 'Duduza Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 92, y: 80 } },
  { id: 'kwathema-g', name: 'KwaThema Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 95, y: 65 } },
  { id: 'benoni-cbd-g', name: 'Benoni CBD Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 90, y: 45 } },
  { id: 'boksburg-g', name: 'Boksburg Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 82, y: 55 } },
  { id: 'brakpan-g', name: 'Brakpan Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 92, y: 55 } },
  { id: 'springs-g', name: 'Springs Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 98, y: 55 } },
  { id: 'nigel-g', name: 'Nigel Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 95, y: 90 } },
  { id: 'heidelberg-g', name: 'Heidelberg Taxi Rank', location: 'South East', category: 'Greater Joburg', coords: { x: 85, y: 95 } },
  { id: 'vereeniging-g', name: 'Vereeniging Taxi Rank', location: 'Vaal', category: 'Greater Joburg', coords: { x: 50, y: 100 } },
  { id: 'vanderbijl-g', name: 'Vanderbijlpark Taxi Rank', location: 'Vaal', category: 'Greater Joburg', coords: { x: 45, y: 100 } },
  { id: 'lenasia-g', name: 'Lenasia Taxi Rank', location: 'South', category: 'Greater Joburg', coords: { x: 10, y: 95 } },
  { id: 'eldorado-g', name: 'Eldorado Park Taxi Rank', location: 'South', category: 'Greater Joburg', coords: { x: 20, y: 90 } },
  { id: 'ennerdale-g', name: 'Ennerdale Taxi Rank', location: 'South', category: 'Greater Joburg', coords: { x: 15, y: 98 } },
  { id: 'orange-farm-g', name: 'Orange Farm Taxi Rank', location: 'South', category: 'Greater Joburg', coords: { x: 30, y: 100 } },
  { id: 'sebokeng-g', name: 'Sebokeng Taxi Rank', location: 'Vaal', category: 'Greater Joburg', coords: { x: 40, y: 100 } },
  { id: 'sharpeville-g', name: 'Sharpeville Taxi Rank', location: 'Vaal', category: 'Greater Joburg', coords: { x: 55, y: 100 } },
  { id: 'evaton-g', name: 'Evaton Taxi Rank', location: 'Vaal', category: 'Greater Joburg', coords: { x: 35, y: 100 } },
  { id: 'devland-g', name: 'Devland Taxi Rank', location: 'South', category: 'Greater Joburg', coords: { x: 35, y: 85 } },
  { id: 'lawley-g', name: 'Lawley Taxi Rank', location: 'South', category: 'Greater Joburg', coords: { x: 5, y: 95 } },
  { id: 'finetown-g', name: 'Finetown Taxi Rank', location: 'South', category: 'Greater Joburg', coords: { x: 25, y: 100 } },
  { id: 'waterval-g', name: 'Waterval Taxi Rank', location: 'Midrand', category: 'Greater Joburg', coords: { x: 62, y: 12 } },
  { id: 'thembisa-g', name: 'Thembisa Taxi Rank', location: 'Ekurhuleni', category: 'Greater Joburg', coords: { x: 86, y: 14 } },
  { id: 'vosloorus-g', name: 'Vosloorus Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 88, y: 75 } },
  { id: 'katlehong-g', name: 'Katlehong Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 82, y: 80 } },
  { id: 'tokoza-g', name: 'Tokoza Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 74, y: 84 } },
  { id: 'reiger-park', name: 'Reiger Park Taxi Rank', location: 'Boksburg', category: 'Greater Joburg', coords: { x: 85, y: 58 } },
  { id: 'boksburg-n', name: 'Boksburg North Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 82, y: 52 } },
  { id: 'benoni-n', name: 'Benoni North Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 90, y: 42 } },
  { id: 'daveyton-g', name: 'Daveyton Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 98, y: 40 } },
  { id: 'etwatwa-g', name: 'Etwatwa Taxi Rank', location: 'East Rand', category: 'Greater Joburg', coords: { x: 100, y: 38 } },
  { id: 'tembisa-e', name: 'Tembisa East Taxi Rank', location: 'Ekurhuleni', category: 'Greater Joburg', coords: { x: 88, y: 16 } },
  { id: 'tembisa-w', name: 'Tembisa West Taxi Rank', location: 'Ekurhuleni', category: 'Greater Joburg', coords: { x: 84, y: 14 } },
  { id: 'olifantsfontein', name: 'Olifantsfontein Taxi Rank', location: 'Midrand', category: 'Greater Joburg', coords: { x: 68, y: 8 } },
  { id: 'centurion', name: 'Centurion Taxi Rank', location: 'Tshwane', category: 'Greater Joburg', coords: { x: 55, y: 5 } },
  
  // East Rand Taxi Ranks
  { id: 'eastgate', name: 'Eastgate Taxi Rank', location: 'Bedfordview', category: 'East Rand', coords: { x: 65, y: 48 } },
  { id: 'east-rand-mall', name: 'East Rand Mall Taxi Rank', location: 'Boksburg', category: 'East Rand', coords: { x: 80, y: 52 } },
  { id: 'lakeside-benoni', name: 'Lakeside Taxi Rank (Benoni)', location: 'Benoni', category: 'East Rand', coords: { x: 88, y: 45 } },
  { id: 'actonville', name: 'Actonville Taxi Rank', location: 'Benoni', category: 'East Rand', coords: { x: 87, y: 47 } },
  { id: 'boksburg-east', name: 'Boksburg East Taxi Rank', location: 'Boksburg', category: 'East Rand', coords: { x: 84, y: 55 } },
  { id: 'brakpan-north', name: 'Brakpan North Taxi Rank', location: 'Brakpan', category: 'East Rand', coords: { x: 92, y: 52 } },
  { id: 'tsakane', name: 'Tsakane Taxi Rank', location: 'Ekurhuleni', category: 'East Rand', coords: { x: 95, y: 70 } },
  { id: 'langaville', name: 'Langaville Taxi Rank', location: 'East Rand', category: 'East Rand', coords: { x: 94, y: 72 } },
  { id: 'springs-central', name: 'Springs Central Taxi Rank', location: 'Springs', category: 'East Rand', coords: { x: 97, y: 53 } },
  { id: 'germiston-lake', name: 'Germiston Lake Taxi Rank', location: 'Germiston', category: 'East Rand', coords: { x: 78, y: 58 } },
  
  // West Rand Taxi Ranks
  { id: 'krugersdorp-north', name: 'Krugersdorp North Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 5, y: 38 } },
  { id: 'kagiso', name: 'Kagiso Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 8, y: 45 } },
  { id: 'mogale-city', name: 'Mogale City Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 10, y: 42 } },
  { id: 'hekpoort', name: 'Hekpoort Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 2, y: 20 } },
  { id: 'magaliesburg', name: 'Magaliesburg Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 1, y: 15 } },
  { id: 'muldersdrift', name: 'Muldersdrift Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 15, y: 15 } },
  { id: 'lanseria', name: 'Lanseria Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 25, y: 5 } },
  { id: 'chartwell', name: 'Chartwell Taxi Rank', location: 'North West', category: 'West Rand', coords: { x: 30, y: 8 } },
  { id: 'broadacres', name: 'Broadacres Taxi Rank', location: 'Fourways', category: 'West Rand', coords: { x: 35, y: 10 } },
  { id: 'dainfern', name: 'Dainfern Taxi Rank', location: 'Fourways', category: 'West Rand', coords: { x: 40, y: 8 } },
  { id: 'randfontein', name: 'Randfontein Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 6, y: 48 } },
  { id: 'westonaria', name: 'Westonaria Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 8, y: 55 } },
  { id: 'carletonville', name: 'Carletonville Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 3, y: 60 } },
  { id: 'fochville', name: 'Fochville Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 5, y: 65 } },
  { id: 'tarlton', name: 'Tarlton Taxi Rank', location: 'West Rand', category: 'West Rand', coords: { x: 12, y: 20 } },
  
  // Northern Suburbs Taxi Ranks
  { id: 'rosebank', name: 'Rosebank Taxi Rank', location: 'Rosebank', category: 'Northern Suburbs', coords: { x: 50, y: 35 } },
  { id: 'hyde-park', name: 'Hyde Park Taxi Rank', location: 'Sandton', category: 'Northern Suburbs', coords: { x: 55, y: 30 } },
  { id: 'sandton-city', name: 'Sandton City Taxi Rank', location: 'Sandton', category: 'Northern Suburbs', coords: { x: 60, y: 22 } },
  { id: 'rivonia', name: 'Rivonia Taxi Rank', location: 'Sandton', category: 'Northern Suburbs', coords: { x: 65, y: 18 } },
  { id: 'sunninghill', name: 'Sunninghill Taxi Rank', location: 'Sandton', category: 'Northern Suburbs', coords: { x: 68, y: 12 } },
  { id: 'paulshof', name: 'Paulshof Taxi Rank', location: 'Sandton', category: 'Northern Suburbs', coords: { x: 70, y: 10 } },
  { id: 'bryanston', name: 'Bryanston Taxi Rank', location: 'Sandton', category: 'Northern Suburbs', coords: { x: 45, y: 20 } },
  { id: 'morningside', name: 'Morningside Taxi Rank', location: 'Sandton', category: 'Northern Suburbs', coords: { x: 58, y: 15 } },
  { id: 'parkmore', name: 'Parkmore Taxi Rank', location: 'Sandton', category: 'Northern Suburbs', coords: { x: 56, y: 18 } },
  { id: 'greenside', name: 'Greenside Taxi Rank', location: 'North', category: 'Northern Suburbs', coords: { x: 45, y: 38 } },
  { id: 'emmarentia', name: 'Emmarentia Taxi Rank', location: 'North', category: 'Northern Suburbs', coords: { x: 42, y: 40 } },
  { id: 'melville', name: 'Melville Taxi Rank', location: 'Auckland Park', category: 'Northern Suburbs', coords: { x: 44, y: 44 } },
  { id: 'auckland-park', name: 'Auckland Park Taxi Rank', location: 'Auckland Park', category: 'Northern Suburbs', coords: { x: 46, y: 46 } },
  { id: 'braamfontein', name: 'Braamfontein Taxi Rank', location: 'CBD Fringe', category: 'Northern Suburbs', coords: { x: 50, y: 47 } },
  { id: 'hillbrow-n', name: 'Hillbrow Taxi Rank', location: 'Berea', category: 'Northern Suburbs', coords: { x: 52, y: 42 } },
  { id: 'berea', name: 'Berea Taxi Rank', location: 'Berea', category: 'Northern Suburbs', coords: { x: 54, y: 42 } },
  { id: 'yeoville-n', name: 'Yeoville Taxi Rank', location: 'Yeoville', category: 'Northern Suburbs', coords: { x: 58, y: 40 } },
  { id: 'bellevue', name: 'Bellevue Taxi Rank', location: 'Yeoville', category: 'Northern Suburbs', coords: { x: 60, y: 40 } },
  { id: 'observatory', name: 'Observatory Taxi Rank', location: 'East', category: 'Northern Suburbs', coords: { x: 65, y: 42 } },
  { id: 'houghton', name: 'Houghton Taxi Rank', location: 'North', category: 'Northern Suburbs', coords: { x: 55, y: 38 } },
  { id: 'orange-grove', name: 'Orange Grove Taxi Rank', location: 'North East', category: 'Northern Suburbs', coords: { x: 62, y: 35 } },
  { id: 'norwood', name: 'Norwood Taxi Rank', location: 'North East', category: 'Northern Suburbs', coords: { x: 60, y: 35 } },
  { id: 'oaklands', name: 'Oaklands Taxi Rank', location: 'North', category: 'Northern Suburbs', coords: { x: 58, y: 33 } },
  { id: 'highlands-north', name: 'Highlands North Taxi Rank', location: 'North East', category: 'Northern Suburbs', coords: { x: 65, y: 30 } },
  { id: 'waverley', name: 'Waverley Taxi Rank', location: 'North East', category: 'Northern Suburbs', coords: { x: 63, y: 30 } },
  { id: 'savoy-estate', name: 'Savoy Estate Taxi Rank', location: 'North East', category: 'Northern Suburbs', coords: { x: 68, y: 28 } },
  { id: 'alexandra-north', name: 'Alexandra North Taxi Rank', location: 'Alexandra', category: 'Northern Suburbs', coords: { x: 75, y: 22 } },
  { id: 'alexandra-east', name: 'Alexandra East Taxi Rank', location: 'Alexandra', category: 'Northern Suburbs', coords: { x: 80, y: 25 } },
  { id: 'parktown', name: 'Parktown Taxi Rank', location: 'North', category: 'Northern Suburbs', coords: { x: 52, y: 44 } },
  { id: 'parktown-north', name: 'Parktown North Taxi Rank', location: 'North', category: 'Northern Suburbs', coords: { x: 54, y: 40 } },
  { id: 'forest-town', name: 'Forest Town Taxi Rank', location: 'North', category: 'Northern Suburbs', coords: { x: 48, y: 42 } },
  { id: 'linden', name: 'Linden Taxi Rank', location: 'North', category: 'Northern Suburbs', coords: { x: 40, y: 35 } },
  { id: 'blairgowrie', name: 'Blairgowrie Taxi Rank', location: 'North', category: 'Northern Suburbs', coords: { x: 38, y: 32 } },
  { id: 'ferndale', name: 'Ferndale Taxi Rank', location: 'Randburg', category: 'Northern Suburbs', coords: { x: 42, y: 28 } },
  { id: 'kensington', name: 'Kensington Taxi Rank', location: 'East', category: 'Northern Suburbs', coords: { x: 68, y: 50 } },
  { id: 'bedfordview', name: 'Bedfordview Taxi Rank', location: 'East', category: 'Northern Suburbs', coords: { x: 66, y: 46 } },
  { id: 'edenvale', name: 'Edenvale Taxi Rank', location: 'East', category: 'Northern Suburbs', coords: { x: 72, y: 44 } },
  
  // Long Distance Taxi Ranks
  { id: 'burgersfort-ld', name: 'Burgersfort Long Distance Rank', location: 'Limpopo', category: 'Long Distance', coords: { x: 95, y: 10 } },
  { id: 'n1-city-ld', name: 'N1 City Long Distance Rank', location: 'Cape Town/Various', category: 'Long Distance', coords: { x: 5, y: 10 } },
  { id: 'park-ld', name: 'Park Station Long Distance Rank', location: 'Joburg CBD', category: 'Long Distance', coords: { x: 52, y: 45 } },
  { id: 'daveyton-ld', name: 'Daveyton Long Distance Rank', location: 'Ekurhuleni', category: 'Long Distance', coords: { x: 98, y: 35 } },
  { id: 'mofolo-ld', name: 'Mofolo Long Distance Rank', location: 'Soweto', category: 'Long Distance', coords: { x: 18, y: 75 } },
  { id: 'westgate-ld', name: 'Westgate Long Distance Rank', location: 'Roodepoort', category: 'Long Distance', coords: { x: 20, y: 44 } },
  { id: 'randburg-ld', name: 'Randburg Long Distance Rank', location: 'Randburg', category: 'Long Distance', coords: { x: 40, y: 24 } },
  { id: 'midrand-ld', name: 'Midrand Long Distance Rank', location: 'Midrand', category: 'Long Distance', coords: { x: 65, y: 9 } },
  { id: 'pretoria-ld', name: 'Pretoria Long Distance Rank', location: 'Tshwane', category: 'Long Distance', coords: { x: 50, y: 5 } },
  { id: 'germiston-ld', name: 'Germiston Long Distance Rank', location: 'East Rand', category: 'Long Distance', coords: { x: 80, y: 59 } },
  { id: 'boksburg-ld', name: 'Boksburg Long Distance Rank', location: 'East Rand', category: 'Long Distance', coords: { x: 82, y: 54 } },
  { id: 'springs-ld', name: 'Springs Long Distance Rank', location: 'East Rand', category: 'Long Distance', coords: { x: 98, y: 54 } },
  { id: 'vereeniging-ld', name: 'Vereeniging Long Distance Rank', location: 'Vaal', category: 'Long Distance', coords: { x: 50, y: 99 } },
  { id: 'vanderbijl-ld', name: 'Vanderbijlpark Long Distance Rank', location: 'Vaal', category: 'Long Distance', coords: { x: 45, y: 99 } },
  { id: 'heidelberg-ld', name: 'Heidelberg Long Distance Rank', location: 'South East', category: 'Long Distance', coords: { x: 85, y: 94 } },
  { id: 'standerton-ld', name: 'Standerton Long Distance Rank', location: 'Mpumalanga', category: 'Long Distance', coords: { x: 100, y: 90 } },
  { id: 'ermelo-ld', name: 'Ermelo Long Distance Rank', location: 'Mpumalanga', category: 'Long Distance', coords: { x: 100, y: 80 } },
  { id: 'nelspruit-ld', name: 'Nelspruit Long Distance Rank', location: 'Mpumalanga', category: 'Long Distance', coords: { x: 98, y: 70 } },
  { id: 'polokwane-ld', name: 'Polokwane Long Distance Rank', location: 'Limpopo', category: 'Long Distance', coords: { x: 55, y: 2 } },
  { id: 'mafikeng-ld', name: 'Mafikeng Long Distance Rank', location: 'North West', category: 'Long Distance', coords: { x: 5, y: 50 } },
  { id: 'rustenburg-ld', name: 'Rustenburg Long Distance Rank', location: 'North West', category: 'Long Distance', coords: { x: 2, y: 35 } },
  { id: 'mahikeng-ld', name: 'Mahikeng Long Distance Rank', location: 'North West', category: 'Long Distance', coords: { x: 6, y: 50 } },
  { id: 'durban-ld', name: 'Durban Long Distance Rank', location: 'KZN', category: 'Long Distance', coords: { x: 90, y: 100 } },
  { id: 'cape-town-ld', name: 'Cape Town Long Distance Rank', location: 'Western Cape', category: 'Long Distance', coords: { x: 2, y: 100 } },
  { id: 'bloemfontein-ld', name: 'Bloemfontein Long Distance Rank', location: 'Free State', category: 'Long Distance', coords: { x: 50, y: 85 } },
  { id: 'kimberley-ld', name: 'Kimberley Long Distance Rank', location: 'Northern Cape', category: 'Long Distance', coords: { x: 20, y: 90 } },
  { id: 'mbombela-ld', name: 'Mbombela Long Distance Rank', location: 'Mpumalanga', category: 'Long Distance', coords: { x: 92, y: 75 } },
  { id: 'tzaneen-ld', name: 'Tzaneen Long Distance Rank', location: 'Limpopo', category: 'Long Distance', coords: { x: 60, y: 8 } }
];

export const POINT_VALUES = {
  PASSENGER_PING: 15,
  DRIVER_START_TRIP: 20,
  PASSENGER_ARRIVED: 30,
  SUBMIT_PRICE: 25,
  SUBMIT_ROUTE_PATH: 100,
  AFFILIATE_SHARE: 50,
  DRIVER_CONFIRM_PICKUP: 20,
  PASSENGER_CONFIRM_PICKUP: 20,
  MARSHAL_POST_STATUS: 30,
  MARSHAL_PING_FLEET: 25,
  POLICE_ALERT: 20,
  TRAFFIC_JAM_ALERT: 15,
  ALT_ROUTE_ALERT: 25,
  PASSENGER_TALLY: 5,
  PASSENGER_DELIVERY_CONFIRM: 15,
  DRIVER_DELIVERY_CONFIRM: 10,
  DRIVER_CONFIRMED_OFFLOAD_BONUS: 10,
  MARSHAL_SET_PRICE: 40,
  MARSHAL_CORRECT_PRICE: 30,
  MARSHAL_APPROVE_LEGIT: 50,
  TAXI_WASH_UPLOAD: 100,
  TAXI_WASH_LIKE: 10,
  SUBMIT_SUGGESTION: 50,
  ANSWER_FAQ: 25,
  DAILY_STREAK_BONUS: 10
};

// Suspension duration in milliseconds (13 days)
export const SUSPENSION_DURATION = 13 * 24 * 60 * 60 * 1000;

// Link detection regex patterns
export const LINK_PATTERNS = [
  /https?:\/\/[^\s]+/gi,
  /www\.[^\s]+/gi,
  /[a-zA-Z0-9-]+\.(com|co\.za|org|net|io|app|za|africa)\b/gi,
  /t\.me\/[^\s]+/gi,
  /wa\.me\/[^\s]+/gi,
  /bit\.ly\/[^\s]+/gi,
  /tinyurl\.com\/[^\s]+/gi
];

// Explicit content detection keywords (basic - would use AI in production)
export const EXPLICIT_KEYWORDS = [
  'nude', 'naked', 'porn', 'sex', 'xxx', 'explicit', 'nsfw',
  'adult content', 'onlyfans', 'nudes', 'naked pics'
];

// Initial routes data
export const INITIAL_ROUTES: RoutePath[] = [
  {
    id: 'r1',
    originId: 'noord',
    destinationId: 'bara',
    price: 22,
    lastUpdatedBy: 'System',
    path: [{ x: 52, y: 48 }, { x: 48, y: 55 }, { x: 40, y: 65 }, { x: 30, y: 70 }, { x: 25, y: 75 }]
  },
  {
    id: 'r2',
    originId: 'bree',
    destinationId: 'alex-mall',
    price: 18,
    lastUpdatedBy: 'System',
    path: [{ x: 48, y: 52 }, { x: 55, y: 45 }, { x: 65, y: 35 }, { x: 75, y: 30 }, { x: 78, y: 25 }]
  },
  {
    id: 'r3',
    originId: 'park-station',
    destinationId: 'sandton-city',
    price: 30,
    lastUpdatedBy: 'System',
    path: [{ x: 51, y: 46 }, { x: 53, y: 38 }, { x: 58, y: 30 }, { x: 60, y: 22 }]
  },
  {
    id: 'r4',
    originId: 'noord',
    destinationId: 'dube',
    price: 20,
    lastUpdatedBy: 'System',
    path: [{ x: 52, y: 48 }, { x: 45, y: 55 }, { x: 35, y: 62 }, { x: 25, y: 68 }, { x: 20, y: 70 }]
  },
  {
    id: 'r5',
    originId: 'bree',
    destinationId: 'tembisa-plaza',
    price: 25,
    lastUpdatedBy: 'System',
    path: [{ x: 48, y: 52 }, { x: 55, y: 40 }, { x: 65, y: 25 }, { x: 75, y: 18 }, { x: 85, y: 15 }]
  }
];
