import { generateText, Output } from "ai"
import { z } from "zod"
import type { Difficulty } from "@/types/learner"

/**
 * Layer 3: the system that learns about THIS specific player.
 *
 * The client sends a compact summary of what the system has observed
 * (which words this learner has mastered, which they keep missing, how many
 * sessions, etc.). The model returns a briefing addressed to this player and
 * fresh memory hooks for the words they're actually struggling with.
 *
 * No user data goes to the model except what the player generated by playing.
 */

interface BriefingRequest {
  difficulty: Difficulty
  totalSessions: number
  totalWordsCompleted: number
  bestStreak: number
  masteredCount: number
  learningCount: number
  newCount: number
  dueForReviewCount: number
  strugglingWords: { word: string; definition: string; missRate: number }[]
  recentlyMastered: string[]
}

const BriefingSchema = z.object({
  message: z
    .string()
    .describe(
      "A short paragraph (3-5 sentences) addressed directly to this learner. Reference what THEY have actually done. Encouraging but specific. No platitudes."
    ),
  todayFocus: z
    .string()
    .describe("One sentence describing what this learner should focus on this session."),
  focusWords: z
    .array(
      z.object({
        word: z.string().describe("The exact word, lowercase."),
        definition: z.string().describe("A short, clear definition (12 words or fewer)."),
        exampleSentence: z
          .string()
          .describe(
            "A natural example sentence using the word. Calibrate vocabulary to the difficulty level."
          ),
        memoryHook: z
          .string()
          .describe(
            "One short, vivid memory aid (8-15 words). Could be a mnemonic, image, or association. Avoid clichés."
          ),
      })
    )
    .describe("Memory hooks for the struggling words the learner sent in. Cover up to 4 words."),
})

export async function POST(req: Request) {
  let body: BriefingRequest
  try {
    body = (await req.json()) as BriefingRequest
  } catch {
    return Response.json({ error: "Invalid JSON body" }, { status: 400 })
  }

  const summary = buildSummaryText(body)
  const focusList = body.strugglingWords.slice(0, 4)

  // Try Layer 3 (AI). If the AI Gateway is unavailable (e.g. no billing on file),
  // we still deliver a real, data-driven briefing using a deterministic fallback,
  // so the layered learning experience never goes dark.
  try {
    const result = await generateText({
      model: "openai/gpt-5-mini",
      system:
        "You are a vocabulary coach inside a Tetris game. The player has been spelling English words from falling letter blocks. " +
        "You receive a summary of what THIS specific player has actually done so far. Your job is to talk to THEM, not generic learners. " +
        "Reference real numbers from the summary. Keep tone warm, focused, and concise.",
      prompt:
        `Here is the data the system has observed about this learner:\n\n${summary}\n\n` +
        (focusList.length > 0
          ? `Generate memory hooks for these specific words they keep missing: ${focusList
              .map((w) => `"${w.word}" (${w.definition})`)
              .join(", ")}.\n\n`
          : "") +
        "Produce the briefing now.",
      experimental_output: Output.object({ schema: BriefingSchema }),
    })

    const output = result.experimental_output

    return Response.json({
      generatedAt: Date.now(),
      difficulty: body.difficulty,
      source: "ai" as const,
      message: output.message,
      todayFocus: output.todayFocus,
      focusWords: output.focusWords,
    })
  } catch (error) {
    console.error("[v0] coach briefing AI call failed, falling back to deterministic briefing:", error)
    const fallback = buildDeterministicBriefing(body)
    return Response.json({
      generatedAt: Date.now(),
      difficulty: body.difficulty,
      source: "fallback" as const,
      ...fallback,
    })
  }
}

/**
 * Deterministic briefing built straight from the learner's data.
 * Used when the AI layer is unavailable. Still personalized — just rule-based.
 */
function buildDeterministicBriefing(body: BriefingRequest) {
  const isFirstSession = body.totalSessions === 0
  const hasStruggles = body.strugglingWords.length > 0
  const hasMastery = body.masteredCount > 0

  let message: string
  if (isFirstSession) {
    message =
      "Welcome. The system hasn't seen you play yet, so this first session is calibration — every word you complete or miss teaches it what to show you next."
  } else if (hasStruggles && hasMastery) {
    message =
      `You've completed ${body.totalWordsCompleted} words across ${body.totalSessions} session${body.totalSessions === 1 ? "" : "s"}, ` +
      `with ${body.masteredCount} mastered and a best streak of ${body.bestStreak}. ` +
      `A few words are still tripping you up — today's session will weight them heavier so they actually stick.`
  } else if (hasMastery) {
    message =
      `${body.masteredCount} words mastered and a best streak of ${body.bestStreak}. ` +
      `No clear struggle pattern right now, so the system will mix in fresh words to push your range.`
  } else {
    message =
      `${body.totalSessions} session${body.totalSessions === 1 ? "" : "s"} so far, ${body.totalWordsCompleted} words completed. ` +
      `Keep going — the system needs a few more reps before the picture sharpens.`
  }

  let todayFocus: string
  if (body.dueForReviewCount > 0) {
    todayFocus = `${body.dueForReviewCount} word${body.dueForReviewCount === 1 ? " is" : "s are"} due for review — they'll show up first.`
  } else if (hasStruggles) {
    todayFocus = `Locking in the words you've been missing: ${body.strugglingWords
      .slice(0, 3)
      .map((w) => w.word)
      .join(", ")}.`
  } else {
    todayFocus = "Stretching your range with new words while the system watches for patterns."
  }

  const focusWords = focusList(body).map((w) => ({
    word: w.word,
    definition: w.definition,
    exampleSentence: `Try using "${w.word}" in a sentence today — for example: "${capitalize(w.word)} matters here."`,
    memoryHook: `Miss rate ${Math.round(w.missRate * 100)}% — your brain keeps slipping on this one. Slow down when it falls.`,
  }))

  return { message, todayFocus, focusWords }
}

function focusList(body: BriefingRequest) {
  return body.strugglingWords.slice(0, 4)
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1)
}

function buildSummaryText(body: BriefingRequest): string {
  const lines: string[] = []
  lines.push(`Difficulty: ${body.difficulty}`)
  lines.push(`Sessions played: ${body.totalSessions}`)
  lines.push(`Total words completed across all sessions: ${body.totalWordsCompleted}`)
  lines.push(`Best streak ever: ${body.bestStreak}`)
  lines.push(
    `Mastery distribution -> mastered: ${body.masteredCount}, learning: ${body.learningCount}, new: ${body.newCount}`
  )
  lines.push(`Words currently due for review: ${body.dueForReviewCount}`)

  if (body.strugglingWords.length > 0) {
    lines.push("")
    lines.push("Words this learner keeps missing:")
    for (const w of body.strugglingWords.slice(0, 6)) {
      lines.push(`  - "${w.word}" (miss rate: ${Math.round(w.missRate * 100)}%) — ${w.definition}`)
    }
  } else {
    lines.push("No struggle pattern yet — they haven't missed anything notable.")
  }

  if (body.recentlyMastered.length > 0) {
    lines.push("")
    lines.push(`Recently mastered: ${body.recentlyMastered.join(", ")}`)
  }

  return lines.join("\n")
}
