/**
 * Layer 2 / Layer 3 data model.
 *
 * Layer 1 (book): same word list for everyone.
 * Layer 2 (movie): we capture per-learner signals (exposures, completions, misses, time-to-spell)
 * and use them to drive flows that are specific to THIS learner.
 * Layer 3 (video game): the AI coach reads accumulated stats and responds to this learner
 * with a personalized briefing + memory hooks.
 */

import type { WordData } from "./game"

export type Difficulty = "easy" | "medium" | "hard"

/**
 * Spaced-repetition + struggle stats for a single word, scoped to a learner.
 * Loosely based on SM-2 but simplified for short, gamified sessions.
 */
export interface WordStat {
  wordId: string
  word: string
  definition: string
  difficulty: Difficulty

  /** 0 = brand new, 5 = mastered. */
  mastery: number
  /** SM-2 easiness factor. Lower = harder for this learner. */
  easiness: number
  /** Minutes until this word is due for review again. */
  intervalMinutes: number

  exposures: number
  completes: number
  misses: number

  /** Average time-to-complete in milliseconds (only counts successful completions). */
  avgCompleteMs: number

  firstSeenAt: number
  lastSeenAt: number
  /** Epoch ms when this word should re-enter the active rotation. */
  nextDueAt: number
}

export type LearnerEvent =
  | { type: "session_started"; at: number; difficulty: Difficulty }
  | { type: "session_ended"; at: number; difficulty: Difficulty; wordsCompleted: number; durationMs: number }
  | { type: "word_shown"; at: number; wordId: string; word: string }
  | { type: "word_completed"; at: number; wordId: string; word: string; timeToCompleteMs: number }
  | { type: "word_missed"; at: number; wordId: string; word: string; reason: "timeout" | "game_over" | "skipped" }

/**
 * The full learner profile. This is the "data the system has about THIS player"
 * that Layer 3 uses to actually learn and adapt.
 */
export interface LearnerProfile {
  id: string
  createdAt: number
  updatedAt: number

  totalSessions: number
  totalWordsCompleted: number
  bestStreak: number

  /** Per-word stats, keyed by word id. */
  wordStats: Record<string, WordStat>

  /** Last N events (capped) — useful for the AI to spot recent patterns. */
  recentEvents: LearnerEvent[]

  /** Cached AI briefing for the most recent pre-game screen. */
  lastBriefing: CoachBriefing | null
}

/**
 * Layer-3 output. The AI coach reads the profile and produces this.
 * It is cached so subsequent visits don't hit the API every time.
 */
export interface CoachBriefing {
  generatedAt: number
  difficulty: Difficulty
  /** Where this briefing came from. "ai" = generated by Layer 3 model; "fallback" = deterministic rules used because AI was unavailable. */
  source: "ai" | "fallback"
  /** A short, human paragraph addressed to this specific learner. */
  message: string
  /** Today's planned focus, in one sentence. */
  todayFocus: string
  /** Per-struggle-word memory hooks. */
  focusWords: FocusWord[]
}

export interface FocusWord {
  word: string
  definition: string
  /** AI-generated example sentence calibrated to this learner's level. */
  exampleSentence: string
  /** A short, vivid memory hook. */
  memoryHook: string
}

/** Lightweight summary used by the menu + briefing screens. */
export interface LearnerSummary {
  totalWordsCompleted: number
  totalSessions: number
  bestStreak: number
  masteredCount: number
  learningCount: number
  newCount: number
  dueForReviewCount: number
  strugglingWords: WordStat[]
  recentlyMastered: WordStat[]
}

/** Helper: bucket a word stat by mastery level. */
export type MasteryBucket = "new" | "learning" | "mastered"

export function bucketOf(stat: WordStat | undefined): MasteryBucket {
  if (!stat || stat.exposures === 0) return "new"
  if (stat.mastery >= 4) return "mastered"
  return "learning"
}

export function makeNewWordStat(word: WordData, difficulty: Difficulty, now: number): WordStat {
  return {
    wordId: word.id,
    word: word.word,
    definition: word.definition,
    difficulty,
    mastery: 0,
    easiness: 2.5,
    intervalMinutes: 0,
    exposures: 0,
    completes: 0,
    misses: 0,
    avgCompleteMs: 0,
    firstSeenAt: now,
    lastSeenAt: now,
    nextDueAt: now,
  }
}
